About Me!

Name - Srividhya S Date - 01/03/2026 Id no - IITP_AIMLTN_2601051

Ecommerce Sales Analysis

This notebook analyzes synthetic e-commerce sales data to understand performance across regions, product categories, and salespersons.

In [1]:
import pandas as pd
import random

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)
print(df.head(10))
print(f"\nDataset shape: {df.shape}")

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

## Task 1: Basic Grouping and Aggregations

This section analyzes the dataset using simple groupby operations to summarize sales by region, category, and salesperson.

1) Calculates the total sales revenue generated in each region and sorts the results to identify the highest performing region.

In [2]:
region_sales = df.groupby('region')['sales_amount'].sum().reset_index()
region_sales

  region  sales_amount
0   East      95189.81
1  North     135181.16
2  South     158977.36
3   West     109383.07

2. Counts how many transactions occurred in each product category.

In [3]:
category_transactions = df.groupby('category')['transaction_id'].count().reset_index()

category_transactions

        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

3. Calculates the average sales value generated by each salesperson.

In [4]:
salesperson_avg = df.groupby('salesperson')['sales_amount'].mean().reset_index()

salesperson_avg

  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

4. For each result, we have used reset_index() to convert the result into a clean DataFrame.

5. Sort the regional sales results in descending order using sort_values(ascending=False) to identify the top-performing region

In [5]:
region_sales_sorted = region_sales.sort_values(by='sales_amount', ascending=False)

region_sales_sorted

  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81

## Task 2: Multi-Column Grouping and Multiple Aggregations

Perform advanced grouping analysis:

1. Group by both region AND category to calculate total sales for each combination using:

In [6]:
sales_region_category_grouped = df.groupby(['region', 'category'])['sales_amount'].sum().reset_index()

sales_region_category_grouped

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

2. For each salesperson, calculate three metrics simultaneously using the agg() method:
Total sales ('sum')
Average sales ('mean')
Number of transactions ('count')
Use this syntax:

In [7]:
salesperson_metrics = df.groupby('salesperson')['sales_amount'].agg(['sum','mean','count']).reset_index()
salesperson_metrics

  salesperson        sum         mean  count
0       Alice   43965.51  1998.432273     22
1         Bob   81757.41  2554.919063     32
2       Carol   68722.32  2454.368571     28
3       David  123436.64  2743.036444     45
4        Emma   82284.09  2493.457273     33
5       Frank   98565.43  2464.135750     40

3. Sort the salesperson results by total sales in descending order to identify the top performer

In [10]:
salesperson_metrics_sorted = salesperson_metrics.sort_values(by='sum', ascending=False)
salesperson_metrics_sorted.head(1)

  salesperson        sum         mean  count
3       David  123436.64  2743.036444     45

4. Use .idxmax() on the grouped category sales to find which category has the maximum total revenue

In [12]:
category_sales = df.groupby('category')['sales_amount'].sum()
top_category = category_sales.idxmax()
top_category

'Electronics'

##Task 3: Custom Aggregation and Complete Sales Report

1. Define a custom aggregation function that calculates the sales range (max - min) for each group:

In [13]:
def sales_range(x):
    return x.max() - x.min()

2. Apply this custom function along with standard aggregations to analyze sales by region:

In [14]:
analysis_by_region = df.groupby('region')['sales_amount'].agg(['sum','mean','min','max',sales_range]).reset_index()
analysis_by_region

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

3. Create a final summary report that shows for each region:

Total number of transactions (using customer_id with count)
Total sales amount
Average transaction value
Use dictionary syntax in agg():

In [17]:
summary = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean'],
    'customer_id': 'count'
}).reset_index()
summary

  region sales_amount              customer_id
                  sum         mean       count
0   East     95189.81  2213.716512          43
1  North    135181.16  2413.949286          56
2  South    158977.36  2789.076491          57
3   West    109383.07  2485.978864          44

4. Explain the multi-level column structure that results from the dictionary-based aggregation and how it differs from single aggregations

The dictionary-based aggregation creates a **multi-level column index** because multiple metrics are calculated for the same column.

For example:
- sales_amount → sum
- sales_amount → mean

This produces hierarchical column names such as:

sales_amount | sum  
sales_amount | mean  

This differs from single aggregations because a simple groupby with one function produces a single flat column.

region | sales_amount